name=Technoshield-ui-lib
version=1.1.0
author=Jean-Sebastien Castonguay <jscastonguay@gmail.com>
maintainer=Aimeric Bouillon <aimericb2004@gmail.com>
sentence=Technoshield User Interface API.
paragraph=Technoshield User Interface board adds LCD, LED, buttons, microSD and an RTC to your Arduino.
category=Display
url=https://github.com/aimericb2004/technoshield-ui-lib
architectures=avr
includes=Technoshield_ui.h
